services:
  backend:
    build: ./backend
    container_name: recon-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: recon-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
